# Generated by Django 3.2.3 on 2021-12-24 08:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0004_product_filter'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='filter',
            field=models.CharField(choices=[('DRINKS', 'DRINKS'), ('FAST-FOOD', 'FAST-FOOD'), ('UZBEK', 'UZBEK'), ('SALADS', 'SALADS')], max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='image',
            field=models.ImageField(upload_to='product/%Y/%m/%d'),
        ),
    ]
