# Generated by Django 3.2.3 on 2021-12-24 09:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0006_contact_your_text'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact',
            name='your_text',
            field=models.CharField(max_length=200),
        ),
    ]
